// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:494027383066:web:eaa9c89fde4ae15de54ca3',
    messagingSenderId: '494027383066',
    projectId: 'spasht-868bd',
    authDomain: 'spasht-868bd.firebaseapp.com',
    databaseURL: 'https://spasht-868bd-default-rtdb.firebaseio.com',
    storageBucket: 'spasht-868bd.firebasestorage.app',
    measurementId: 'G-QJQ82FRL5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:494027383066:android:14e8559a9603255fe54ca3',
    messagingSenderId: '494027383066',
    projectId: 'spasht-868bd',
    databaseURL: 'https://spasht-868bd-default-rtdb.firebaseio.com',
    storageBucket: 'spasht-868bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:494027383066:ios:95cc5cd781480ac2e54ca3',
    messagingSenderId: '494027383066',
    projectId: 'spasht-868bd',
    databaseURL: 'https://spasht-868bd-default-rtdb.firebaseio.com',
    storageBucket: 'spasht-868bd.firebasestorage.app',
    iosBundleId: 'com.mycompany.spasht',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:494027383066:ios:95cc5cd781480ac2e54ca3',
    messagingSenderId: '494027383066',
    projectId: 'spasht-868bd',
    databaseURL: 'https://spasht-868bd-default-rtdb.firebaseio.com',
    storageBucket: 'spasht-868bd.firebasestorage.app',
    iosBundleId: 'com.mycompany.spasht',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:494027383066:web:3969fd65b4024ba2e54ca3',
    messagingSenderId: '494027383066',
    projectId: 'spasht-868bd',
    authDomain: 'spasht-868bd.firebaseapp.com',
    databaseURL: 'https://spasht-868bd-default-rtdb.firebaseio.com',
    storageBucket: 'spasht-868bd.firebasestorage.app',
    measurementId: 'G-YC2L5B6FC0',
  );
}
